### ISSUE TITLE
Data file

### ISSUE THREAD

**Issue by Leo-wu96** [KYHKL-H/Epidemic-Simulator#1]
I found in your open source project that a data file is needed for running, but unfortunately I did not find it. I hope you can provide me with a copy. I am very interested in your project and hope to further study it. Thanks！

**Comment by KYHKL-H** [comment]
> I found in your open source project that a data file is needed for running, but unfortunately I did not find it. I hope you can provide me with a copy. I am very interested in your project and hope to further study it. Thanks！

I am sorry that we can not provide the data file due to privacy reasons and agreements with the data provider. You can use dataset in your own city or simply generate a small toy data randomly, according to the data form in readme. Hopefully our project can help you and more information is available in our research paper 'Understanding the Urban Pandemic Spreading Using Real World Mobility Data', published in the proceedings of KDD'20.
